#basic options
title: Northwestern Football Analytics
author: ncaldwell17
email: noahcaldwell-gatsos2019@u.northwestern.edu
description: Machine Learning Final Project

#Build settings 
markdown: kramdown
theme: jeykyll-theme-midnight
show_downloads: false

#Navigation Bar Options
navbar-links:
  Visualizations:https:ncaldwell17.github.io/NU-Football/visualizations
  
#Default YAML Values
defaults:
    scope:
      path: all files
    values:
      layout: "page"
      show-avatar: true
      
#plugins
plugins:
  - jeykyll-sitemap


