#basic options
title: Northwestern-Football-Analytics
author: ncaldwell17
email: noahcaldwell-gatsos2019@u.northwestern.edu
email: vamsibanda2020@u.northwestern.edu
email: ericyang2015@u.northwestern.edu
description: site for ML final project

#Build settings 
markdown: kramdown
theme: minima

   
