#basic options
title: Northwestern-Football-Analytics
author: ncaldwell17
email: noahcaldwell-gatsos2019@u.northwestern.edu
description: site for ML final project

#Build settings 
markdown: kramdown
theme: minima
baseurl: "/northwestern_football"
url: "ncaldwell17.github.io" 
   
