#basic options
title: Northwestern-Football-Analytics
author: ncaldwell17
email: noahcaldwell14@yahoo.com
description: site for ML final project

#Build settings 
markdown: kramdown
theme: minima

   
