#basic options
title: Northwestern Football Analytics
author: ncaldwell17
email: noahcaldwell-gatsos2019@u.northwestern.edu
description: Machine Learning Final Project
url: "http://ncaldwell17.github.io/NU-Football"
baseurl: "/NU-Football"

#Build settings 
markdown: kramdown
theme: jeykyll-theme-midnight
show_downloads: false

#Navigation Bar Options
navbar-links:
  About Me: "aboutme"
  Visualizations2: "visualizations"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"
  Visualizations: "https:ncaldwell17.github.io/NU-Football/visualizations"
  
#Default YAML Values
defaults:
    scope:
      path: all files
    values:
      layout: "page"
      show-avatar: true
      
#plugins
plugins:
  - jeykyll-sitemap
  - jeykyll-paginate 


